# Copyright 2024 The dm_control Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or  implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ============================================================================

"""Muscle groups for the dog model."""

LATERAL = [
    "m_abdominis_Aponeurosis",
    "m_depressor_caudae_brevis_L",
    "m_depressor_caudae_brevis_L2",
    "m_depressor_caudae_brevis_L2(2)",
    "m_depressor_caudae_brevis_R",
    "m_depressor_caudae_brevis_R2",
    "m_depressor_caudae_brevis_R2(2)",
    "m_intercostals_ext_L",
    "m_intercostals_ext_R",
    "m_intercostals_int_L",
    "m_intercostals_int_R",
    "m_latissimus_dors_L",
    "m_latissimus_dors_R" "m_levator_caudae_brevis_L",
    "m_levator_caudae_brevis_L1",
    "m_levator_caudae_brevis_L2",
    "m_levator_caudae_brevis_R",
    "m_levator_caudae_brevis_R1",
    "m_levator_caudae_brevis_R2",
    "m_Ligament",
    "m_longissimus_capitis_L",
    "m_longissimus_capitis_R(2)",
    "m_longissimus_thoracis_L",
    "m_longissimus_thoracis_R",
    "m_obliquus_ext_abdominis_L",
    "m_obliquus_ext_abdominis_R",
    "m_obliquus_int_abdominis_L",
    "m_obliquus_int_abdominis_R",
    "m_psoas_major_L",
    "m_psoas_minor_L",
    "m_psoas_major_R",
    "m_psoas_minor_R",
    "m_rectus_abdominis_R",
    "m_rectus_abdominis_L",
    "M_Thoracis_M_Pectoralis_Profundus",
    "m_transverses_thoracis_L",
    "m_transverses_thoracis_R",
    "m_tranversus_abdominis_L",
    "m_tranversus_abdominis_R",
]

TO_SKIP = [
    "m_orbicularis_oculi",
    "m_Skutulum_L",
    "m_temporalis_L",
    "m_zygomaticus_L",
    "m_masseter_L",
    "m_orbicularis_oris_L",
    "m_geniohyoideus_L",
    "m_caninus_L",
    "m_levator_labii_sup_L",
    "m_buccinator_L(2)",
    "m_buccinator_L",
    "m_Eye_L",
    "m_retractor_anguli_oculi_L",
    "m_pterygoideus_med_L",
    "m_pterygoideus_lat_L",
    "m_rectus_capitis_ventr_L",
    "m_rectus_capitis_lateralis_L",
    "m_transverses_thoracis_L",
    "m_rectus_thoracis_L",
    "m_digastricus_L",
    "m_Skutulum_R",
    "m_temporalis_R",
    "m_zygomaticus_R",
    "m_masseter_R",
    "m_orbicularis_oris_R",
    "m_geniohyoideus_R",
    "m_caninus_R",
    "m_levator_labii_sup_R",
    "m_buccinator_R(2)",
    "m_buccinator_R",
    "m_Eye_R",
    "m_retractor_anguli_oculi_R",
    "m_pterygoideus_med_R",
    "m_pterygoideus_lat_R",
    "m_rectus_capitis_ventr_R",
    "m_rectus_capitis_lateralis_R",
    "m_transverses_thoracis_R",
    "m_rectus_thoracis_R",
    "m_digastricus_R",
    "m_flexor_digitorum_superficialis_L",
]

FLEXORS_BACK = [
    "m_flexor_digitorum_superficialis_L.001",
    "m_semitendinosus_L",
    "m_adductor_magnus_L",
    "m_gracilis_L",
    "m_biceps_femoris_L",
    "m_abductor_cruris_L",
    "m_tibialis_caudalis_L",
    "m_gastrocnemius_L",
    "m_peroneus_brevis_L",
    "m_semimembranosus_L",
    "m_flexor_digitorum_profundus_L(2)",
    "m_flexor_digitorum_superficialis_R",
    "m_semitendinosus_R",
    "m_adductor_magnus_R",
    "m_gracilis_R",
    "m_biceps_femoris_R",
    "m_abductor_cruris_R",
    "m_tibialis_caudalis_R",
    "m_gastrocnemius_R",
    "m_peroneus_brevis_R",
    "m_semimembranosus_R",
    "m_flexor_digitorum_profundus_R(2)",
]

FLEXORS_FRONT = [
    "m_teres_major_L",
    "m_triceps_brachii_long_L(2)",
    "m_flexor_capri_radialis_L",
    "m_triceps_brachii_medial_L",
    "m_triceps_brachii_long_L",
    "m_triceps_brachii_lateral_L",
    "m_tensor_f.antebrachii_L",
    "m_triceps_brachii_accessory_L",
    "m_flexor_digitorum_profundus_L",
    "m_teres_major_R",
    "m_triceps_brachii_long_R(2)",
    "m_flexor_capri_radialis_R",
    "m_triceps_brachii_medial_R",
    "m_triceps_brachii_long_R",
    "m_tricepsbrachii_lateral_R",
    "m_tensor_f.antebrachii_R",
    "m_triceps_brachii_accessory_R",
    "m_flexor_digitorum_profundus_R",
]

EXTENSORS_BACK = [
    "m_extensor_digitorum_longus_L",
    "m_tibialis_cranialis_L",
    "m_sartorius_L(2)",
    "m_peroneus_longus_L",
    "m_vastus_lat_ander_fascia_lata_L",
    "m_rectus_femoris_L",
    "m_biceps_femoris_tendon_L",
    "m_sartorius_L",
    "m_gluteus_superficialis_major_L",
    "m_extensor_digitorum_lateralis_L",
    "m_pectineus_L",
    "m_extensor_digitorum_longus_R",
    "m_tibialis_cranialis_R",
    "m_sartorius_R(2)",
    "m_peroneus_longus_R",
    "m_vastus_lat_ander_fascia_lata_R",
    "m_rectus_femoris_R",
    "m_biceps_femoris_tendon_R",
    "m_sartorius_R",
    "m_gluteus_superficialis_major_R",
    "m_extensor_digitorum_lateralis_R",
    "m_pectineus_R",
]

EXTENSORS_FRONT = [
    "m_biceps_brachii_L",
    "m_deltoideus_acromialis_L",
    "m_extensor_digitorum_lat_L",
    "m_extensor_capri_ulnaris_L",
    "m_extensor_digitorum_communis_L",
    "m_subscapularis_L",
    "m_infraspinatus_L",
    "m_supraspinatus_L",
    "m_abductor_pollicis_longus_L",
    "m_brachialis_L",
    "m_extensor_capri_radialis_L",
    "m_biceps_brachii_R",
    "m_deltoideus_acromialis_R",
    "m_extensor_digitorum_lat_R",
    "m_extensor_capri_ulnaris_R",
    "m_extensor_digitorum_communis_R",
    "m_subscapularis_R",
    "m_infraspinatus_R",
    "m_supraspinatus_R",
    "m_abductor_pollicis_longus_R",
    "m_brachialis_R",
    "m_extensor_capri_radialis_R",
]

NECK = [
    "m_Ligament",
    "m_longus_capitis_L",
    "m_splenius_L",
    "m_sternohyroideus_L",
    "m_sternothyroideus_R",
    "m_longissimus_cervicis_R",
    "m_rhomboideus_R",
    "m_sternocephalicus_L",
    "m_longissimus_capitis_L(2)",
    "m_omotransversarius_L",
    "m_thoracis_serratus_ventr_R",
    "m_longissimus_capitis_R",
    "m_sternocephalicus_R",
    "m_omotransversarius_R",
    "m_thoracis_serratus_ventr_L",
    "m_longus_capitis_R",
    "m_splenius_R",
    "m_sternohyroideus_R",
    "m_sternothyroideus_L",
    "m_longissimus_cervicis_L",
    "m_rhomboideus_L",
]

TORSO = [
    "m_longissimus_thoracis_L",
    "m_longissimus_capitis_L",
    "m_longissimus_thoracis_R",
    "m_longissimus_capitis_R(2)",
    "m_psoas_minor_L",
    "m_obliquus_ext_abdominis_R",
    "m_tranversus_abdominis_L",
    "m_psoas_major_L",
    "m_obliquus_ext_abdominis_L",
    "m_tranversus_abdominis_R",
    "m_psoas_major_R",
    "m_psoas_minor_R",
]

TAIL = [
    "m_levator_caudae_longus_R",
    "m_levator_caudae_brevis_R2",
    "m_depressor_caudae_brevis_R2",
    "m_depressor_caudae_brevis_L2",
    "m_levator_caudae_brevis_L2",
    "m_depressor_caudae_brevis_L",
    "m_depressor_caudae_brevis_R2(2)",
    "m_depressor_caudae_brevis_R",
    "m_levator_caudae_longus_L",
    "m_depressor_caudae_brevis_L2(2)",
]
